### ISSUE TITLE
set_tags() can't handle byte-array auxiliary tags

### ISSUE THREAD

**Issue by dpryan79** [pysam-developers/pysam#406]
This is originally from [biostars](https://www.biostars.org/p/236819/). If you try to `set_tags()` using a byte array then the following error is produced:

    Traceback (most recent call last):
      File "./foo.py", line 9, in <module>
        read.set_tags(tags)
      File "pysam/libcalignedsegment.pyx", line 2113, in pysam.libcalignedsegment.AlignedSegment.set_tags (pysam/libcalignedsegment.c:23066)
      File "pysam/libcalignedsegment.pyx", line 295, in pysam.libcalignedsegment.packTags (pysam/libcalignedsegment.c:6217)
    ValueError: invalid value type 'B' (<type 'str'>)

I'm attaching a very very small BAM file (it and the index are in the zip file) that can produce this error with the following code:

    #!/usr/bin/env python
    import pysam

    bam = pysam.AlignmentFile("small.bam")
    for read in bam.fetch():
        tags = read.get_tags(with_value_type=True)
        read.set_tags(tags)

I've tried earlier version (back to 0.8.4) and none of these are able to handle this sort of situation.

[example.zip](https://github.com/pysam-developers/pysam/files/777372/example.zip)

**Comment by clmin** [comment]
Ok, I suppose it would work?
How can I change my package pysam with this?

**Comment by dpryan79** [comment]
@clmin: If possible, I would wait until this pull request is approved and a new version of pysam is available (this ensures that my proposed changes don't break anything). If you really need this fixed now then you'll need to clone my fork, switch to the `fix406` branch and `pip install . --user --upgrade`. I hope that that will fix the issues, though I didn't run it on the full dataset you uploaded.

**Comment by clmin** [comment]
Ok, thanks.

**Comment by AndreasHeger** [comment]
Thanks, both.

The fix will be in the next release. I think htslib 1.4 is imminent, so it should not be too far off.

**Comment by clmin** [comment]
Hello,
I checked for the htslib 1.4, it was updated yesterday.
I downloaded and installed it (make install in the correct path), and I also made a general update/upgrade (sudo apt-get...).
However, I still have the same error.
Did I do something incorrectly?
